# Generated by Django 5.0.2 on 2024-02-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cistern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=300)),
                ('current_volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MilkFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('cistern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkinfo.cistern')),
            ],
        ),
    ]
